apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
type: Opaque
data:
  client-passwords: cHN3ZEthZmth
  controller-password: cHN3ZEthZmth
  inter-broker-password: cHN3ZEthZmth
  system-user-password: cHN3ZEthZmth
