apiVersion: v1
kind: Secret
metadata:
  name: orders-db-secret
type: Opaque
data:
  username: b3JkZXJzLWFwcA== #base64 для "orders-app"
  password: c2ltcGxlX3Bhc3N3b3Jk  #base64 для "simple_password"
  database: b3JkZXJzX2Ri #base64 для orders_db